### PR TITLE
Add Translation Portuguese-BR & Spanish

### PR DESCRIPTION
**Pull request by crashzk**
- Add Translation Portuguese-BR & Spanish

### CODE REVIEW

**Comment by B3none** [comment]
Hello, please put the translations files in their respective folders for this to be merged.

**Comment by crashzk** [comment]
> Hello, please put the translations files in their respective folders for this to be merged.

Done...

**Comment by B3none** [comment]
I'm concerned that putting the Brazilian Portuguese translations as Portuguese could upset Portuguese people. I am however happy to accept the Spanish translation 👍

**Comment by crashzk** [comment]
> I'm concerned that putting the Brazilian Portuguese translations as Portuguese could upset Portuguese people. I am however happy to accept the Spanish translation 👍

About the Spanish translation, perfect.

The Portuguese-Brazilian translation does not understand the problem, since Portuguese-PT is another, like this in SourceMod's own config: **_(csgo\addons\sourcemod\configs)_**
```
"Languages"
{
	"pt"		"Brazilian"		// (24) Brazilian Portuguese
	"pt_p"		"Portuguese"		// (40) Portuguese
}
```
I never understood why they and most users translate "PT" translations as if they were Portuguese-PT.

**Comment by B3none** [comment]
Well pointed out, good work! I’ll merge this shortly.

**Review by B3none — APPROVED** [review]

**Pull request merged**
